# Generated by Django 3.2.3 on 2021-10-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
