# Generated by Django 3.2.3 on 2021-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/user-image-min.jpg', upload_to='userprofile'),
        ),
    ]
